### ISSUE TITLE
Did not check() all arguments during publisher 'questions'

### ISSUE THREAD

**Issue by nadeemja** [Kurounin/Pagination#1]
Hi,

After carefully following your instructions for my Questions collection, I'm getting the following error in my server log.

    Exception from sub questions id zw2ARJsNHwec2GArw Error: Did not check() all arguments during publisher 'questions'
    I20151213-15:17:03.176(1)?     at [object Object]._.extend.throwUnlessAllArgumentsHaveBeenChecked (packages/check/match.js:411:1)
    I20151213-15:17:03.177(1)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:106:1)
    I20151213-15:17:03.177(1)?     at maybeAuditArgumentChecks (livedata_server.js:1695:18)
    I20151213-15:17:03.178(1)?     at [object Object]._.extend._runHandler (livedata_server.js:1023:17)
    I20151213-15:17:03.178(1)?     at [object Object].subscriptionProto._runHandler (packages/meteorhacks_kadira/lib/hijack/wrap_subscription.js:12:1)
    I20151213-15:17:03.181(1)?     at [object Object]._.extend._startSubscription (livedata_server.js:842:9)
    I20151213-15:17:03.182(1)?     at [object Object]._.extend.protocol_handlers.sub (livedata_server.js:614:12)
    I20151213-15:17:03.182(1)?     at packages/meteorhacks_kadira/lib/hijack/wrap_session.js:77:1
    I20151213-15:17:03.182(1)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    I20151213-15:17:03.182(1)?     at [object Object].sessionProto.protocol_handlers.sub (packages/meteorhacks_kadira/lib/hijack/wrap_session.js:76:1)

Also, on the frontend, the questions show up and disappear without any errors in the javascript console.

**Comment by Kurounin** [comment]
Hi,

The error seems to be thrown by the package meteorhacks_kadira. Can you try disabling that package?

**Comment by Kurounin** [comment]
On a second overview I think the error is caused by the usage of the package audit-argument-checks. Did you include this package in your meteor app?

**Comment by nadeemja** [comment]
Yes, but to include the package is best-practice.
Also, the package is not known to break functionality, as far as I know.

There must be some other reason as to why documents appear and disappear on
the frontend.
What do you think?

*/Nadeem J. Qureshi,*
Daglig leder, Sembly
452 22 604, nadeemjq@sembly.no

**Comment by Kurounin** [comment]
I've updated the package so it will not throw errors when used with audit-argument-checks package.
