### ISSUE TITLE
Meteor.users ?

### ISSUE THREAD

**Issue by odesey** [Kurounin/Pagination#10]
Does this package work with the `Meteor.users` collection? I tried the following :

`new Meteor.Pagination(Meteor.users);`

and get the following error:
```
TypeError: Cannot read property '_name' of undefined
at Pagination.publish (packages/kurounin_pagination/server/pagination.js:11:1)
```

Also tried 
`new Meteor.Pagination(Schemas.users);` (because I am using simple schema but get the same error).

Thanks.

**Comment by Kurounin** [comment]
I just tested the pagination using `new Meteor.Pagination(Meteor.users);` and it works.
Make sure you included one of the accounts packages (_accounts-password_, _accounts-facebook_, _accounts-github_, _accounts-google_, _accounts-meetup_, _accounts-twitter_, or _accounts-weibo_) or at least the _accounts-base_ package.

**Comment by odesey** [comment]
Thanks for your response, I accidentally placed the `new Meteor.Pagination(Meteor.users);` in a client folder. Moved it server side and the error  went away.

Thanks!
