### ISSUE TITLE
Question: what is the best way to pass a "limit" parameter from the client to the server?

### ISSUE THREAD

**Issue by carlosalvidrez** [Kurounin/Pagination#101]
I'd just like to control the total maximum number of records the server should fetch for the client.
Wondering if a "limit" clause would work, or if I should think of this as a product of the number of items per page and the page number in turn.

Thanks!

**Comment by Kurounin** [comment]
You can set the limit either on init:
```javascript
Template.myList.onCreated(function () {
    this.pagination = new Meteor.Pagination(MyCollection, {
        perPage: 20
    });
});
```
or by calling after init
```javascript
this.pagination.perPage(20);
```
The default number of records returned is 10.

The documents returned is calculated like this:
- from: `skip()` + `perPage()` * (`currentPage()` -1)
- to: `skip()` + `perPage()` * `currentPage()`

**Comment by carlosalvidrez** [comment]
Thanks! Can I buy you a cup of coffee? Let me know if you have any sort of donation/fund-me page. 
I've been using your library and are very grateful that you not only shared it, but you still respond to issues/questions. 
Cheers!

**Comment by Kurounin** [comment]
There's no need to donate, but I appreciate the thought. I'm happy with contributing to the open source scene that I'm relying on so often myself.
