### ISSUE TITLE
Could the package be modified to use "aggregate" and not "find"?

### ISSUE THREAD

**Issue by carlosalvidrez** [Kurounin/Pagination#102]
Wondering if there might be any plans to do this.
Aggregations would allow one to use Mongo Atlas Search, and also have a number of new querying features available.
Let me know if you might have any pointers or ideas.

Thanks!

**Comment by Kurounin** [comment]
I haven't been using meteor for a few years, so I don't know if it would be feasible to do this, but from my knowledge using aggregation won't allow you to use mongo tail, so there won't be any reactive updates when the data changes.

**Comment by carlosalvidrez** [comment]
Got it, thank you for getting back to me. 
And thank you for the work you put into this, I still use your library : )
