### ISSUE TITLE
pagination.ready() never true

### ISSUE THREAD

**Issue by odesey** [Kurounin/Pagination#11]
I am having the same issue as issue #4 . I used the following:

```javascript
Template.myList.helpers({
    isReady: function () {
        console.log( Template.instance().pagination.ready() );
        return Template.instance().pagination.ready();
    },
    templatePagination: function () {
        return Template.instance().pagination;
    },
    documents: function () {
        return Template.instance().pagination.getPage();
    }
});
```

and in my template the one difference is that I am using `{{#with documents}}` instead of `{{#each documents }}` 

The `console.log( Template.instance().pagination.ready() )` runs once `false` and never runs again.

Using the solution mentioned in #4 does work however.

**Comment by Kurounin** [comment]
The ready state is modified when calling _getPage_ method. You could try a little hack: in the _onCreated_ method, after you instantiate the pagination set the ready to true ( `self.pagination.ready(true)` ) , so on the first run the condition _{{#if isReady}}_ will evaluate to true, the _documents_ helper will be called and ready will be set to false and again to true when the documents are fetched.

**Comment by odesey** [comment]
Thanks for the work around.
