### ISSUE TITLE
Page Jumps to top on clicked link

### ISSUE THREAD

**Issue by odesey** [Kurounin/Pagination#12]
As per this SO answer, it would be nice to get an option in the init object to define the href value as `#/` instead of `#` to prevent page jumps when clicking page numbers and prev/next.

http://stackoverflow.com/questions/3252730/how-to-prevent-a-click-on-a-link-from-jumping-to-top-of-page-in-jquery

**Comment by Kurounin** [comment]
Thanks for suggestion.
I published a new version which implements the callback `onClick` that is called right before changing the page. The default callback calls e.preventDefault().
For more info, on how you can implement the callback, check https://github.com/Kurounin/PaginationBlaze

**Comment by odesey** [comment]
Awesome, thank you for the quick response and solution.
