### ISSUE TITLE
Meteor.users + Search

### ISSUE THREAD

**Issue by odesey** [Kurounin/Pagination#13]
How would I go about implementing a  search feature combined with your package for Meteor.users()? I am already using the `filters` field to narrow the list of users to paginate based on other aspects of the app like so:
`filters: { '_id': { '$in': org.membership.current } }`

This works perfectly. 

Now if I wanted to search the users, do I need to modify the `filters:' field to pass the search text? If so how would that query look.

Also on the server side, do I need to setup indexes to handle the fields that should be searched of will the pagination package handle that as well?

Thanks.

**Comment by Kurounin** [comment]
Indexes need to be added by you, either from MongoDb or from Meteor server side using 
```js
MyCollection.rawCollection().createIndex({field_to_index: 1}, function (error, result) {});
```
or if you use https://github.com/aldeed/meteor-collection2 or https://github.com/aldeed/meteor-schema-index set `index: true` for that field.

If you want to allow for additional filtering, you can add an event when the search form is submitted (or when the input is changed):
```js
Template.myList.events({
    'submit #searchForm': function (e, templateInstance) {
        e.preventDefault();

        const searchedValue = $.trim(templateInstance.$('#searchInput').val()).replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g, "\\$&");
        const currentFilters = templateInstance.pagination.filters();

        if (searchedValue.length > 0) {
            currentFilters.username = { $regex: search, $options: "i"};
        } else {
            delete currentFilters.username;
        }

        templateInstance.pagination.filters(currentFilters);
    }
});
```

**Comment by odesey** [comment]
This works, thanks for the response.

Last question ( I hope :-) ).

I need to be able to search multiple fields at once, so I set `index: true` to those fields in `collection-2` and adjusted the filter like so:

```javascript
  currentFilters['profile.lastName'] = { $regex: searchedValue, $options: 'i'};
  currentFilters['profile.firstName'] = { $regex: searchedValue, $options: 'i'};

  template.pagination.filters(currentFilters);
```

I also tried this:
```javascript
    currentFilters.profile = {
      lastName: { $regex: searchedValue, $options: 'i'},
      firstName: { $regex: searchedValue, $options: 'i'}
    }

  template.pagination.filters(currentFilters);
```

and this:

```javascript
  currentFilters.profile = {
    $or: [
      { lastName: { $regex: searchedValue, $options: 'i'} },
      { firstName: { $regex: searchedValue, $options: 'i'} }
    ]
  };
```

I get no results when I try the examples listed above.

I do get results if I only do one field however:
`currentFilters['profile.lastName'] = { $regex: searchedValue, $options: 'i'};`

It works as expected.

**Comment by odesey** [comment]
Ok I think I got it, this seems to work for multiple fields:

```javascript
  const currentFilters =  { '_id': { '$in': org.membership.current }, $and : [
      { $or: [
          {'profile.lastName': { $regex: searchedValue, $options: 'i' } },
          {'profile.firstName': { $regex: searchedValue, $options: 'i' } },
          //additional fields to search go here
        ],
      }
      ]
    };

template.pagination.filters(currentFilters);
```

If there is another way I should be doing this please feel free to let me know.

Thanks again for the help.

**Comment by Kurounin** [comment]
You should be able to use only the $or operator, so it would be like:
```js
Template.myList.events({
    'submit #searchForm': function (e, templateInstance) {
        e.preventDefault();

        const searchedValue = $.trim(templateInstance.$('#searchInput').val()).replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g, "\\$&");
        const currentFilters = templateInstance.pagination.filters();

        if (searchedValue.length > 0) {
            currentFilters.$or = [
                {'profile.lastName': { $regex: searchedValue, $options: 'i' } },
                {'profile.firstName': { $regex: searchedValue, $options: 'i' } },
                //additional fields to search go here
            ];
        } else {
            delete currentFilters.$or;
        }

        templateInstance.pagination.filters(currentFilters);
    }
});
```

**Comment by odesey** [comment]
Thanks you, this works as well and is probably faster because it uses less operators.
