### ISSUE TITLE
Server side filters

### ISSUE THREAD

**Issue by odesey** [Kurounin/Pagination#14]
This is more of a request.

It would be nice to be able to filter the data from the server side for security reasons. Based on my use of the package thus far, the `filter` is the only thing preventing the user from accessing all the documents in a given collection. This is handled on the client side, so if the client changes the filter they can get access to all the documents in that given collection.

Is there anyway to hard-code the filters from the server side?

**Comment by Kurounin** [comment]
At the moment there's no possibility to hard-code filters on the server-side. I'll look into adding this feature as soon as I can.

**Comment by Kurounin** [comment]
I published a new version. You can now provide a set of filters on the server side or even dynamic filters, which can not be overridden (e.g. server/publications.js):
```js
new Meteor.Pagination(MyCollection, {
    filters: {is_enabled: true},
    dynamic_filters: function () {
        return {user_id: this.userId};
    }
});

```

**Comment by odesey** [comment]
Thanks for the quick response! I will test and provide feedback.
