### ISSUE TITLE
Infinite Scroll?

### ISSUE THREAD

**Issue by wesleyfsmith** [Kurounin/Pagination#21]
I'm wondering what it would take to build infinite scroll instead of doing pages.

Great package BTW. Been looking for something to replace pages that works with react.

**Comment by Kurounin** [comment]
It could be done with the current package, by adding an event in your layout when you are reaching the end of the displayed list, which should call the `perPage()` method to increase the current number of displayed document.

**Comment by wesleyfsmith** [comment]
Awesome. Amazing library by the way @Kurounin . I plan on making some PRs once I get more familiar with it.

**Comment by Kurounin** [comment]
Glad you like it. Feel free to submit a PR if you find some way to improve it.
