### ISSUE TITLE
ES6 with createContainer()

### ISSUE THREAD

**Issue by wesleyfsmith** [Kurounin/Pagination#22]
I'm having an issue with the library and using the ES6 syntax. The problem is that createContainer() doesn't have a reference to the instance of the component that is doing the pagination. As a result, I have to move the pagination object to an external scope. This makes it so that I can't reuse the component multiple times on the same page though because all components would have the same reference to the pagination object.

Hopefully, this gives you a better idea of what my code currently looks like. I have comments in the parts I want to change.

Thanks!

```javascript

let Pagination = new Meteor.Pagination(Appointments);

class FindAppointmentsPaginated extends React.Component {
  constructor(props) {
    //This is where I want to insantiace the meteor pagination object
  }
  renderAppointment(appointment) {
    return (
      <div className="row" key={appointment._id}>
        <div className="col-md-12">
          <p>
            {appointment.services.toString()}
          </p>
      </div>
     </div>
    );
  }
  render () {
    return(
      <div>
        {this.props.appointments.map(this.renderAppointment)}
        <BootstrapPaginator
                  pagination={Pagination}
                  limit={10}
                  containerClass="text-center"
                  />
      </div>
    );
  }
}

export default createContainer(() => {
  //I want to access the component instance's pagination object here, instead of the external one I made

  return {
    ready: Pagination.ready(),
    appointments: Pagination.getPage()
  };
}, FindAppointmentsPaginated);

```

**Comment by Kurounin** [comment]
I haven't had time to work with the new react and es6 syntax, but i believe you could do it by adding an extra component which encapsulates the creation of the pagination instance.
Take a look at the example project I created https://github.com/Kurounin/PaginationReactExample/blob/master/client/main.jsx
