### ISSUE TITLE
Regex filters not working correctly?

### ISSUE THREAD

**Issue by SpyridonZ** [Kurounin/Pagination#27]
I've used other pagination packages and typically they accept regex filters (same as MongoDB does naturally) to find partial matches/case insensitivity.

For example, if inputting "Val"

var regexed = new RegExp(attributes.code, "i");

Would return any case insensitive matches ("val" or "VAL"), as well as any partial matches ("value").

But if I input regex filters in to this package, the results are empty.

Any ideas on how to resolve?

(EDIT: I found the closed issue related to this! Sorry for posting! Will toggle this issue as closed!)

**Comment by luixal** [comment]
In case someone get here and don't want to go searching for the issue @SpyridonZ talks about, here you have: #2
