### ISSUE TITLE
pagination.ready() never true - Still an issue

### ISSUE THREAD

**Issue by SpyridonZ** [Kurounin/Pagination#28]
Similar issue to #11  except the solution is NOT working. Using a modified version of demo project.

My helpers:

```
Template.hello.helpers({
    isReady: function () {
        console.log("isReady: " +  Template.instance().pagination.ready() );
        return Template.instance().pagination.ready();
    },
    templatePagination: function () {
        return Template.instance().pagination;
    },
    documents: function () {
        return Template.instance().pagination.getPage();
    },
	clickEvent: function() {
		return function(e, templateInstance, clickedPage) {
			e.preventDefault();
			console.log('Changing page from ', templateInstance.data.pagination.currentPage(), ' to ', clickedPage);
		};
	},

});
```

onCreated:

`this.pagination = new Meteor.Pagination(MyCollection, {
        filters: {

        },
        sort: {

        },
        perPage: 20
    });

    this.pagination.ready(true);`

HTML:

`{{#if isReady}}

            <ul>
                {{#each documents}}
                    <li>{{title}} - Brand: {{brand}} - Code: {{code}} - Number: {{number}} - isTrue: {{isTrue}}</li>
                {{/each}}
            </ul>

            {{> defaultBootstrapPaginator pagination=templatePagination limit=5 containerClass="text-left" onClick=clickEvent}}

        {{else}}
            Loading...
        {{/if}}`

Regarding the solution to #11, you can see I added the item in to the onCreated.

But the console.log outputs:

http://screencast.com/t/1F8nru9T3o

If I remove the if isReady block, everything works perfectly.

So it seems that isReady is never actually setting itself to true, even though all the data is actually ready.

According to console.log (included in screenshot) you can see it briefly set as true from the onCreated, but it gets set back to false, and never true again...

**Comment by SpyridonZ** [comment]
Did a little more research, would like to add:

Neither of the solutions you have provided in #11 work.

The only solution that does work at all, is the solution from tcastelli in #4 

The solutions you provided after tcastelli do not work.

**Comment by Kurounin** [comment]
Thanks for the heads up. I haven't really used the ready() method so I didn't noticed issue.
I've published a new version of the package & updated the https://github.com/Kurounin/PaginationExample repository to include the ready usage.
Now it's straightforward to use the method and subscription requests to the server are minimized.
