### ISSUE TITLE
How to create multiple publications for same collection or pass parameters to publications?

### ISSUE THREAD

**Issue by ankitv89** [Kurounin/Pagination#30]
I have multiple publications defined for different roles and routes. This is to keep the data published limited to the type of route. I was able to do this by filtering it on the client side, but for added security, I want to do this on server side. 

Presently, I am able to do this with multiple publications, how to replicate the same using this package?

**Comment by ankitv89** [comment]
Sent a [pull request](https://github.com/Kurounin/Pagination/pull/31) for the same. have a look.

**Comment by Kurounin** [comment]
If you have different fields available to clients based on their access level (roles) you can implement on server side the `transform_options` function to limit the returned fields, based on the logged in user.

**Comment by ankitv89** [comment]
Hi, yes, that is a way of doing it, but in some cases, we have a requirement of written a completely different function which would have resulted in couple of 'if-else' blocks. It would have worked eventually but again, it more manageable through different  function. Anyway, I have mitigated the issue as in the referenced pull request. I will close the issue now!
