### ISSUE TITLE
Set current Page

### ISSUE THREAD

**Issue by mladendinev** [Kurounin/Pagination#34]
I've been trying to set the current page by taking the page number from my url. According to your documentation 

    documents() {
       var pageNumb = Number(FlowRouter.getQueryParam('page'))
      return Template.instance().pagination.currentPage(pageNumb);
    },

should set the page to "pageNumb",but the method currentPage return type is "Int", not object with all docs for this particular page.

**Comment by Kurounin** [comment]
That method is not supposed to return the documents, only set the page and return the newly set page number.
If you want to set the page from url, you should set it when initializing, In your template javascript file (e.g. client/scripts/mylist.js):
```
Template.myList.onCreated(function () {
    this.pagination = new Meteor.Pagination(MyCollection, {
        page: Number(FlowRouter.getQueryParam('page')),
        sort: {
            _id: -1
        }
    });
});
```
and use the `getPage()` method to return the documents in a helper:
```
Template.myList.helpers({
    documents: function () {
        return Template.instance().pagination.getPage();
    }
});
```

If for some reason (the page is not available when instantiating) you want to set the page after initializing the pagination component you can use:
```
templateInstance.pagination.currentPage(pageNumb);
```
but still get documents in a helper, using the `Template.instance().pagination.getPage()` method.
