### ISSUE TITLE
Pagination subscriptions still active after temlate is destroyed

### ISSUE THREAD

**Issue by brylie** [Kurounin/Pagination#35]
When attaching a Pagination subscription to a Blaze template instance, the subscription remains active even after the template is destroyed. This bug seems to have been introduced in version 1.0.16.

# Screencast
![peek 2017-01-12 13-47](https://cloud.githubusercontent.com/assets/17307/21888617/b3de2cbc-d8cd-11e6-8ba7-291764a7851d.gif)

**Comment by Kurounin** [comment]
Thanks for the bug report.
I published a new version which fixes this, both on Blaze templates & in ReactJS. Re-open the bug if you still have issues.
