### ISSUE TITLE
expose a destroy() or at least a Tracker stop or some way to gracefully stop all computation

### ISSUE THREAD

**Issue by zeroasterisk** [Kurounin/Pagination#36]
I keep getting notified that my react component has un-mounted by something is trying to set internal state.  

I think exposing a hook I can call on `componentWillUnmount` would be very nice, for me to explicitly kill any subscription and computation you've got going.

Thoughts?

**Comment by Kurounin** [comment]
Sure, I could add a method which forcefully unsubscribes, but are you sure it's because of this component since I'm using Tracker to keep a list of all observers and unsubscribe automatically when the react component is unmounted.

**Comment by Kurounin** [comment]
I published a new version which should fix (see #39)  this issue. Reopen if it is still a problem.
