### ISSUE TITLE
Initial load - somehow getting un-subscribed

### ISSUE THREAD

**Issue by zeroasterisk** [Kurounin/Pagination#37]
I can sometimes recreate this, but have not yet made an easy reproducible example. (sorry)

Basic summary:

*on initial page load*

- browser loads client
- client starts resume-token login auth & subscribes to current user
- auth in progress & React shows a loading placeholder
- auth completes & my React page loads
- React page loads a Component wrapped with a HOC which implements Pagination clientside
- pagination sets up the subscription
- meteor transfers records to minimongo
- during transfer, React component receives new props (unsure what at this point)
- pagination un-subscribes but doesn't re-subscribe
- client trashes records from minimongo

![ss](https://puu.sh/urSTE/73d0075d51.png)
![ss](https://puu.sh/urSRW/4a38bf844f.png)

After that, if I can change pages and change back, without reloading the browser, it all works great

----

I suspect the next step would be to add more debugging inside pagination client `_checkObservers`.

I was just interested if you had any idea what was going on or what I should be trying out to get to the bottom of this.

**Comment by Kurounin** [comment]
Could you try replicating this behaviour in https://github.com/Kurounin/PaginationReactExample ? From the screenshots you posted I don't see any console log regarding the unsubscribe event which should be triggered from this line https://github.com/Kurounin/Pagination/blob/master/client/pagination.js#L129 
You could add more console.log calls inside the _checkObservers method to see how the `this._activeObservers` property is getting modified

**Comment by Kurounin** [comment]
Can you check if it is still an issue with the latest #39 fix?

**Comment by zeroasterisk** [comment]
yup - I believe this is resolved --- thanks @marla-singer !!
