### ISSUE TITLE
pagination.ready() not reactive

### ISSUE THREAD

**Issue by tcastelli** [Kurounin/Pagination#4]
I have noticed that assigning pagination.ready() to a ReactiveVar doesn't keep reactivity,
I think in order to make it work, the handle should be stored instead:
so it will be this.ready(handle) instead of this.ready(handle.ready()) and then it will keep reactivity on the outside :)

As a workaround, i have defined a helper like this to check for ready state
````js
 pageReady:function(){
        var instance = Template.instance();
        var pagesChange = instance.pagination.getPage();
        return instance.pagination.ready();
    }
````

**Comment by Kurounin** [comment]
The ready() function is reactive. You're probably not using it correctly.
There are 2 ways to go about it (using the example given in the documentation):
### First possibility, which is the most straightforward
In your template javascript file (e.g. client/scripts/mylist.js):
`
Template.myList.helpers({
    isReady: function () {
        return Template.instance().pagination.ready();
    },
    templatePagination: function () {
        return Template.instance().pagination;
    },
    documents: function () {
        return Template.instance().pagination.getPage();
    }
});
`
In your template file:
`<template name="myList">
    <div>
        {{#if isReady}}
            <ul>
              {{#each documents}}
                  <li>Document #{{_id}}</li>
              {{/each}}
            </ul>
            {{> defaultBootstrapPaginator pagination=templatePagination limit=10 containerClass="text-center"}}
        {{else}}
            <i class="fa fa-spinner fa-spin"></i>
        {{/if}}
    </div>
</template>
`

### Second possibility, which is a roundabout way
`
Template.myList.created = function () {
    this.pagination = new Meteor.Pagination(MyCollection, {
        sort: {
            _id: -1
        }
    });

    this.isReady = new ReactiveVar(this.pagination.ready());

    this.autorun(() => {
        this.isReady.set(this.pagination.ready());
    });
}

Template.myList.helpers({
    isReady: function () {
        return Template.instance().isReady().get();
    },
    templatePagination: function () {
        return Template.instance().pagination;
    },
    documents: function () {
        return Template.instance().pagination.getPage();
    }
});
`

In either cases, if you put a _console.log()_ in the isReady helper function you will see it is called every time the pagination creates a new subscription (for cached pages the previous used subscription is used so the ready variable does not change).
