### ISSUE TITLE
How to publish dependable collection?

### ISSUE THREAD

**Issue by jaganreddy** [Kurounin/Pagination#42]
Hi 

In client onCreated I am using following code

```
this.pagination = new Meteor.Pagination(Ads, {
  	sort: {
    				_id: -1
        	},
		perPage: 1,
		filters:conditions,
		fields:{"images":1,"adlocation":1,"title":1,"slug":1}
  });
```

In server publish 

```
new Meteor.Pagination(Ads,{
	transform_options: function (filters, options) {
        const fields = { "images":1,"adlocation":1,"title":1,"slug":1 }
        options.fields = _.extend(fields, options.fields);
        return options;
    }
});
```

Defined images in Ads schema like

```
images: {
    type: [String],
    optional: true,
    label: "Pictures",
    autoform: {
      afFieldInput: {
        type: "cfs-files",
        collection: "images"
      }
    }
  },
```
How to fetch(subscribe) images from images collection with same pagination. 

I am struggling with the solution.
Please help me

Regards,
Jagan

**Comment by Kurounin** [comment]
Hi,

You need to first publish on the server side the wanted documents/images, if you don't have it available from an autoform plugin. For example, something like this:
```
Meteor.publish('autoformFileDoc', function(collectionName, docId) {
  check(collectionName, String);
  check(docId, String);

  const collection = FS._collections[collectionName] || global[collectionName];

  if (collection) {
    return collection.find({
      _id: docId,
      // 'metadata.owner': this.userId
    });
  }
});
```

In your client side, in the onCreated function add an autorun function to subscribe to the needed documents/images:
```
this.autorun(() => {
  const ads= this.pagination.getPage();

  _.each(ads, function(ad) {
    _.each(ad.images, function (id) {
      Meteor.subscribe('autoformFileDoc', "images", id);
    });
  });
});
```

You can also change the publish function to accept an array, so you do just one subscribe with all the ids from the client side.

**Comment by jaganreddy** [comment]
Thanks a lot Kurounin, I will try this way.
I implemented temporarily by created new template for image view which is included in ads template each loop. In on created method of imageview template I am subscribing individual image almost similar to your explaination by passing image id.

**Comment by MohammedEssehemy** [comment]
@Kurounin 
this code sample will consume increasing memory because of the following 2 issues:
1- in each autorun loop you create new subscription page and will not cancel subscriptions from the previous loop.
2- you are using Meteor.subscribe which will not be stopped the subscription after the template destroyed [check here](http://blazejs.org/api/templates.html#Blaze-TemplateInstance-subscribe)

**Comment by Kurounin** [comment]
@MohammedEssehemy 
To avoid memory leaks you can change the client side code to
```javascript
Template.Ads.onCreated(function() {
  this.pagination = new Meteor.Pagination(Ads);
  const pagination = this.pagination;

  this.autorun(function () {
    const ads= pagination.getPage();

    _.each(ads, (ad) => {
      _.each(ad.images, (id) => {
        this.subscribe('autoformFileDoc', "images", id);
      });
    });
  });
});
```
which will stop the subscription when the template is destroyed, according to the docs:
> You can use this.subscribe from an onCreated callback to specify which data publications this template depends on. The subscription is automatically stopped when the template is destroyed.

**Comment by MohammedEssehemy** [comment]
@Kurounin yup, that's what I meant.
