### ISSUE TITLE
Make subscription non reactive

### ISSUE THREAD

**Issue by mgscreativa** [Kurounin/Pagination#44]
Hi! I read elsewhere that passing **reactive: false** as an option to a publication, renders it non reactive, so as that's what I want to several data grids in my project (IE: I don't want a reactive admin only user list data grid) I created the **transform_options** override as this:
```
new Meteor.Pagination(Documents, {
  name: 'documents.paginatedList',
  transform_options: (filters, options) => {
    const newOptions = options;

    newOptions.reactive = false;

    return newOptions;
  },
});
```
According to logs, this seems to set the reactive option as I want

> Pagination documents.paginatedList find {} {"fields":{},"sort": {},"skip":100,"limit":10,"debug":true,"reactive":false}

But after testing a little, if I open two browsers and login with different users on each other and then add or modify the published collection on one browser, it updates the data grid in the other browser.

Is it possible to make this great pagination component non reactive by passing some option?

Thanks!

PS: More detailed use case here https://forums.meteor.com/t/meteor-1-5-publication-method-pagination/37240/24

**Comment by Kurounin** [comment]
Hi,

I published a new version which accepts the **reactive** option to allow for non-reactive subscriptions. Keep in mind that any changes to another setting (changing the page, sort order, filter, etc.) will perform another non-reactive subscription and update the results.

**Comment by mgscreativa** [comment]
Great! I have just updated my example wit a non reactive route, and it works! My idea is to subscribe to the user list, but no subscribe the whole data grid, that way I have a chance to show a notification of new users saving some bandwidth and server resources.
