### ISSUE TITLE
Can't set filters or dynamic_filters

### ISSUE THREAD

**Issue by mgscreativa** [Kurounin/Pagination#45]
Hi! I have created a paginated publication and works great! But if I try to add a filter to be able to display collection items from the current logged in user, it returns an empty result.

Maybe it's because I'm getting this.userId as undefined! If i replace this.userId by a current user id string, it works.

This works:
```
  filters: { owner: 'SsZ4uWc5hdH2abisk' },
```
This doesn't:
```
  filters: { owner: this.userId},
```
This is the log I'm getting hardcoding the user id:

> I20170623-19:40:15.777(-3)? Pagination documents.paginatedList reactive publish {"owner":"SsZ4uWc5hdH2abisk"} {"fields":{"title":1,"body":1,"owner":1},"sort":{},"skip":0,"limit":10,"reactive":true,"debug":true}

This is the log I'm getting using this.userId:

> => Meteor server restarted
> I20170623-19:25:26.550(-3)? undefined
> I20170623-19:25:26.556(-3)? Pagination documents.paginatedList reactive publish {"$and":[{},{}]} {"fields":{"title":1,"body":1,"owner":1},"sort":{},"skip":0,"limit":10,"reactive":true,"debug":true}

This is the code in imports/api/documents/server/publications.js

```
new Meteor.Pagination(Documents, {
  name: 'documents.paginatedList',
  filters: { owner: this.userId }, // Seems to be undefined
  dynamic_filters: () => {
    console.log(this.userId); // Got undefined in log

    return (
      { owner: this.userId }
    );
  },
  transform_options: (filters, options) => {
    const newOptions = options;
    const fields = {
      title: 1,
      body: 1,
      owner: 1,
    };

    newOptions.fields = _.extend(fields, newOptions.fields);

    return newOptions;
  },
});
```

Thanks in advise!

**Comment by Kurounin** [comment]
Hi,

By defining dynamic filters like this
```
  dynamic_filters: () => {
    console.log(this.userId); // Got undefined in log

    return (
      { owner: this.userId }
    );
  },
```
The closure keeps the original **context (this)**. Change your code to
```
  dynamic_filters: function() {
    console.log(this.userId); // Got undefined in log

    return (
      { owner: this.userId }
    );
  },
```

**Comment by mgscreativa** [comment]
Well, I can't believe I felt into this dummy arrow function gotcha. I thinks it's always a first time for everything!

Thanks for the review!
