### ISSUE TITLE
Cannot have conflicting publication

### ISSUE THREAD

**Issue by josephpmay** [Kurounin/Pagination#49]
This is not really an issue, but more something I feel should be documented but not sure if it should go in the readme, so I'm not doing a pull request.

pagination.getPage() will return empty if there is a conflicting publication.

 i.e. You can't have in your collections/publications api both 
```javascript
Meteor.publish('myCollection', function {
return MyCollection.find();
});
```
and
```javascript
publishPagination(MyCollection);
```

You can, however, have a secondary publication with another name, such as:
```javascript
Meteor.publish('singleCollectionItem', function(dbID) {
		return MyCollection.findOne({ _id: dbID });
	});
```

**Comment by Kurounin** [comment]
You are right, you need a unique name for publishing the pagination collection. That name can be overridden by setting the name property on init (both on the server and client side).
