### ISSUE TITLE
publishPagination overrides other publications

### ISSUE THREAD

**Issue by ivan133** [Kurounin/Pagination#50]
Hi!
I have publication problem.
Here is my code:
```
Meteor.publish("Sites.showByIdEdit", function(_id) {
  check(_id, String);
  if (!this.userId) return this.ready();
  return Sites.find({_id}, {fields: { 'feild': 1, 'feild': 1}});
});

publishPagination(Sites);
```

So the site has all fields available always.
What can I do to restrict fields?

**Comment by ivan133** [comment]
I fixed it.

```
const MyListPage = React.createClass({
  mixins: [ReactMeteorData],
  pagination: new Meteor.Pagination(Sites,{
      sort: {
        createdAt: -1,
      }
    }
  ),

```
The above code will be executed allways.
I should create new Meteor.Pagination in getInitialState
```
const MyListPage = React.createClass({
  mixins: [ReactMeteorData],

  getInitialState: function() {
    this.pagination = new Meteor.Pagination(Sites,{
        sort: {
          createdAt: -1,
        }
      }
    );
    return{
      column: 'createdAt',
      direction: 'ascending',
    };
  },
```

**Comment by vladbalan** [comment]
@Kurounin I don't think this issue is resolved. Here is my use case:

```js
publishPagination(Items, {
  name: 'items.pagination',
  transform_options: (filters, options) => {
    return { 
      ...options, 
      fields: { 
        _id: 1,
        name: 1,
      } 
    };
  },
});

Meteor.publish('items.byId', function(itemId) {
  return Items.find({ _id: itemId }, { 
    fields: {
      _id: 1,
      veryLargeObject: 1,
    }
  });
});
```

If I subscribe to `items.byId` I don't get the `veryLargeObject`, but I do get the `name` field. In order to get `veryLargeObject` I have to publish it from `items.pagination`, but this is very inefficient (because my paginated items now come with all the extra data). Is there any way around this?

**Comment by Kurounin** [comment]
@vladbalan There is no issue in using multiple publications to publish separate fields, as can be seen in this branch https://github.com/Kurounin/PaginationExample/tree/multiple-publications where the `related_id` field is published by a separate publication only for document with _id **gZeDzFmYHa9hfYjhY**.

The only limitation of Meteor subscription mechanism as stated on their documentation https://docs.meteor.com/api/pubsub.html#Meteor-subscribe is when trying to use different sub-fields
> Currently, when multiple subscriptions publish the same document only the top level fields are compared during the merge. This means that if the documents include different sub-fields of the same top level field, not all of them will be available on the client. We hope to lift this restriction in a future release.
