### ISSUE TITLE
Printing returned document's values to PDF prints nothing

### ISSUE THREAD

**Issue by yushaUzumo** [Kurounin/Pagination#51]
I changed from alethes pagination to kurounin pagination hoping for different/desired results. I am trying to print returned document's values to PDF using meteor add ongoworks:pdf but nothing is printed. Values from normal helper functions do get printed but values from the paginated documents are not being printed

My code is as follows:

import { publishPagination } from 'meteor/kurounin:pagination';
publishPagination(PurchaseHistory);

<template name="invoiceList">
    <div>
        {{#if isReady}}
            <ul>
              {{#each documents}}
                  {{> oneInvoice}}
              {{/each}}
            </ul>
            {{> invoiceForm}}
            {{> defaultBootstrapPaginator pagination=templatePagination limit=10 containerClass="text-center" onClick=clickEvent}}
        {{else}}
            Loading...
        {{/if}}
    </div>
</template>

<template name="oneInvoice">
	<li>Date #{{transactionDate}}</li>
</template>
<template name="invoiceForm">
	<form class="createInvoicePDF">
		<div class="form-group">
			<input class="green-btn" type="submit" id="submit" value="Create PDF"/>
		</div>
	</form>
</template>	

Router.route('/store/invoiceList/:_username/:startingDate/:endingDate', { //:_startingDate/:_endingDate
	name: 'invoiceList',
	template: 'invoiceList',
	onBeforeAction: function()
	{
		var userId = Meteor.userId();
        if (userId)
        {
             this.next();
	},
    data: function(){
		return {};
	},
	waitOn: function() {

		return [Meteor.subscribe('systemInfo'),Meteor.subscribe('testingOn'),Meteor.subscribe('companyAddressNameEmailAndVatNumber')];
	}
});

if (Meteor.isClient) {

//,transactionDate:{$gte:new Date(decodeURIComponent(Router.current().params.username;)),
	//				  $lt:new Date(decodeURIComponent(Router.current().params.username;))}

	Template.invoiceList.onCreated(function () {
		this.pagination = new Meteor.Pagination(PurchaseHistory, {
			filters: {userId:Meteor.userId()},
			sort: {
				transactionDate: 1
			},
			perPage: 1
		});
	});

	Template.invoiceList.helpers({
		isReady: function () {
			return Template.instance().pagination.ready();
		},
		templatePagination: function () {
			return Template.instance().pagination;
		},
		documents: function () {
			return Template.instance().pagination.getPage();
		},
		// optional helper used to return a callback that should be executed before changing the page
		clickEvent: function() {
			return function(e, templateInstance, clickedPage) {
				e.preventDefault();
				console.log('Changing page from ', templateInstance.data.pagination.currentPage(), ' to ', clickedPage);
			};
		}
	});
	
	Template.invoiceForm.events({
		'submit .createInvoicePDF': function (event) {
			event.preventDefault();
		}
	});
	
	Template.invoiceForm.onRendered(function(){
		var validator = $('.createInvoicePDF').validate({//2. remember to attach in the html a required field to all fields that are required
			submitHandler: function(event){
				Blaze.saveAsPDF(Template.oneInvoice, {
				  filename: "Invoice.pdf", // optional, default is "document.pdf"
				  //x: 0, // optional, left starting position on resulting PDF, default is 4 units
				  //y: 0, // optional, top starting position on resulting PDF, default is 4 units
				  orientation: "portrait", // optional, "landscape" or "portrait" (default)
				  //unit: "in", // optional, unit for coordinates, one of "pt", "mm" (default), "cm", or "in"
				  //format: "letter" // optional, see Page Formats, default is "a4"
				  //elementHandlers: specialElementHandlers
				});
			}
		});
	});
}

**Comment by Kurounin** [comment]
Hi,

According to the code in [ongoworks:pdf](https://github.com/ongoworks/meteor-pdf/blob/master/pdf.coffee) the template will be rendered normally using Blaze or with a given data set. Since you are not providing the `data `property the template will render initially with `isReady` being false and will print it, which is why you do not see any documents (the package does not wait for documents to be loaded before printing).

A simple solution would be to create a Template which will receive the paginated results as props, in which case you can create the `pagination` instance and get the data first, before calling `Blaze.saveAsPDF()` with `data` property containing the `pagination.getPage()` data.

**Comment by yushaUzumo** [comment]
I don't fully understand what you are saying. Can you please illustrate with as example.

**Comment by yushaUzumo** [comment]
I have used:

	Template.invoiceList.helpers({
		transactionDate: function () {
			return Template.instance().pagination.getPage()[0].transactionDate;
		}
	});

instead of:

	Template.invoiceList.helpers({
		documents: function () {
			return Template.instance().pagination.getPage();
		}
	});

But the transactionDate is still not printed in the pdf

**Comment by yushaUzumo** [comment]
When I hard code a value it gets printed just fine:

		transactionDate: function () {
			return "Hard coded value"
		},

Please note that I have removed the {{#if isReady}} check

<template name="invoiceList">
    <div>
        
            <ul>
				<li>Date #{{transactionDate}}</li>
			</ul>
			<form class="createInvoicePDF">
				<div class="form-group">
					<input class="green-btn" type="submit" id="submit" value="Create PDF"/>
				</div>
			</form>
            {{> defaultBootstrapPaginator pagination=templatePagination limit=6 containerClass="text-center" onClick=clickEvent}}
    </div>
</template>

**Comment by Kurounin** [comment]
The issue is not the isReady check. Nothing is printed in the pdf because the subscription did not yet returned the documents when you are calling `Template.instance().pagination.getPage()[0].transactionDate;`

What you should do is create a template that has the pagination component and inside it, you should have the invoiceForm. The code can look like this:

**invoiceList.js**
```javascript
Template.invoiceList.onCreated(function () {
});

Template.invoiceList.helpers({
	isReady: function () {
		return Template.instance().pagination.ready();
	},
	templatePagination: function () {
		return Template.instance().pagination;
	},
	documents: function () {
		return Template.instance().pagination.getPage();
	},
	// optional helper used to return a callback that should be executed before changing the page
	clickEvent: function() {
		return function(e, templateInstance, clickedPage) {
			e.preventDefault();
			console.log('Changing page from ', templateInstance.data.pagination.currentPage(), ' to ', clickedPage);
		};
	}
});
```

**invoiceList.html**
```javascript
{{#if isReady}}
        {{> invoiceForm documents=documents}}
{{/if}}
```

**invoiceForm.js**
```javascript
Template.invoiceForm.events({
	'submit .createInvoicePDF': function (event) {
		event.preventDefault();
	}
});

Template.invoiceForm.onRendered(function(){
       var receivedData = this.data;

	var validator = $('.createInvoicePDF').validate({
		submitHandler: function(event){
			Blaze.saveAsPDF(Template.oneInvoice, {
			  filename: "Invoice.pdf", // optional, default is "document.pdf"
			  data: receivedData
			});
		}
	});
});
```

**Comment by yushaUzumo** [comment]
this.data; returns indefine. I changed the statement to
var receivedData = Template.instance().pagination.getPage(); It still does not work.
How will Template.invoiceList.documents know it is supposed to be changed to data=receivedData? 

Have you tried to implement the same scenario as I have. Does it work on your side?

**Comment by Kurounin** [comment]
You can try with `Template.currentData()` instead of `this.data`. `Template.invoiceList` will use `Template.instance().pagination.getPage()` from the helper function and it will pass the documents to `Template.invoiceForm` which in turn when you click the save pdf button should pass the documents to `Template.oneInvoice`.
Create a demo repository if you still can't make it work.
