### ISSUE TITLE
defaultBootstrapPaginator is not working for blaze

### ISSUE THREAD

**Issue by thusila** [Kurounin/Pagination#52]
defaultBootstrapPaginator is not working for blaze when using this package.It's really great if you can create an example for blaze also

**Comment by Kurounin** [comment]
There's already an example repository for the Blaze paginator: https://github.com/Kurounin/PaginationExample

**Comment by thusila** [comment]
Currently I'm using version 1.3 and when using pulishPagination it mentions that there is no such method.What is the reason for that

**Comment by Kurounin** [comment]
There should not be an issue with 1.3. Check reply on https://github.com/Kurounin/PaginationExample/issues/2

**Comment by thusila** [comment]
how many subscribe at the begining

**Comment by Kurounin** [comment]
You can set the number of documents subscribed, by changing the _perPage_ setting.
So you can either do
```javascript
Template.myList.onCreated(function () {
    this.pagination = new Meteor.Pagination(MyCollection, {
        perPage: 50
    });
});
```
or you can change the perPage later dynamically
```javascript
Template.instance().pagination.perPage(50);
```
