### ISSUE TITLE
Semantic UI

### ISSUE THREAD

**Issue by tcollins590** [Kurounin/Pagination#53]
Is it possible to load with semantic UI css rather than bootstrap?

**Comment by Kurounin** [comment]
Neither Pagination or PaginationBlaze have any dependencies to bootstrap package. PaginationBlaze uses the default classes defined in bootstrap and supports dynamically defining the class for the wrapper element: https://github.com/Kurounin/PaginationBlaze/blob/master/client/template.html
From what I see on the examples page https://semantic-ui.com/collections/menu.html#pagination semantic ui uses different class names. I can add the option to set custom class names for the various elements included in the PaginationBlaze template.

**Comment by Kurounin** [comment]
I published a new version which will allow setting custom classes https://github.com/Kurounin/PaginationBlaze/commit/e246eb87efec92f724dfd53e43c0a853cc6f44be
To get the semantic ui look, you need to use it like this:
```html
{{> defaultBootstrapPaginator pagination=templatePagination limit=10 paginationClass="ui pagination menu" itemClass="item" wrapLinks=false}}
```

**Comment by tcollins590** [comment]
Hi @Kurounin 

Thank you for posting this. When I paste the template example from your previous comment I get.
I have just done `kurounin:pagination-blaze` do I need to install a special way in order to get your update?

![image](https://user-images.githubusercontent.com/28879452/30762818-8adb862e-9fb1-11e7-925a-c40d21eda58f.png)

Thank you

**Comment by Kurounin** [comment]
From the screenshot you provided, it seems like it's still generating `<li>` tags. Are you using latest version (1.0.4) of pagination-blaze? Check the _.meteor/versions_ file to see and change the used version.

**Comment by tcollins590** [comment]
I have confirmed that I am using 1.0.4. Do I need to explicitly import
blaze-pagination into my template? I also still use defaultBootstrapPaginator
correct?  





On Mon, Sep 25, 2017 3:06 AM, Kurounin notifications@github.com  wrote:
From the screenshot you provided, it seems like it's still generating <li> 
tags. Are you using latest version (1.0.4) of pagination-blaze? Check the 
.meteor/versions  file to see and change the used version.

**Comment by tcollins590** [comment]
If I remove the semantic UI classes and leave the default classes, I am left with a list the pages. 
Is this normal?

![image](https://user-images.githubusercontent.com/28879452/30840449-55aa2f64-a245-11e7-9916-c98f789b489b.png)

**Comment by tcollins590** [comment]
It looks like the code is generating a <ul> with <li> inside. Semantic UI calls for a Div with the pagination and menu classes and <a> for each button. 

Any ideas?

**Comment by tcollins590** [comment]
[](https://github.com/tcollins590/PaginationBlaze/blob/master/client/template.html)
This got it working. Take a look.

**Comment by Kurounin** [comment]
I checked again and wrapLinks option was not working properly for the page links. I published a new version which fixed this issue. Please upgrade to 1.0.5.
