### ISSUE TITLE
Data Tables related with Kurounin pagination

### ISSUE THREAD

**Issue by group22dsl** [Kurounin/Pagination#54]
I used this pagination to integrate subscription base pagination in my meteor app.  Its work perfectly. But now I want to convert my all tables to the data tables. How can I do it?
Thanks

**Comment by Kurounin** [comment]
The goal of this package is to provide an easy way to get reactive paginated data, based on custom filters and options. You could integrate it with a data table, if you can hook the data table events (sorting, filtering, changing page, etc.) to your own custom functions which will call the appropriate methods on the pagination instance.
I personally did not try any data table package, as I created custom views/tables for each of the projects in which I used this package, so I can't recommend any.

If you do find a good data table package with which you can integrate this, you can post here the solution and I can add it to the readme.
