### ISSUE TITLE
Define is not defined error when setup Kurouning pagination

### ISSUE THREAD

**Issue by group22dsl** [Kurounin/Pagination#59]
When I trying to setup kurouning pagination in my meteor app it shows error like "define is not defined". Please can you give me some solution for this. 

I think it comes up with this code 

`this.bookPagination = new Meteor.Pagination(Books, {
        sort: {
            title: 1
        },
        reactive: true
  });`

**Comment by Kurounin** [comment]
If you search the code base, there is no **define** keyword used anywhere. Most likely the error stems from somewhere else. 
For an implementation example check https://github.com/Kurounin/PaginationExample
