### ISSUE TITLE
Can't stop subscription when changing route

### ISSUE THREAD

**Issue by luchux** [Kurounin/Pagination#6]
So, If the paginator is created inside a "Template.created: -> " instance, then when I change the route, the paginator is still publishing the data. 

Is there a way to stop the publication in other routes? I expected to be destroyed. 

Thanks

**Comment by Kurounin** [comment]
The problem was caused by the [ccorcos:subs-cache](https://github.com/ccorcos/meteor-subs-cache) package which didn't stop the subscription after the set timeout (5 minutes).
I've removed the package since it is no longer maintained.
