### ISSUE TITLE
After updating a record, data not updated reactively

### ISSUE THREAD

**Issue by n00bvn** [Kurounin/Pagination#62]
Hi,
I found out really strange error. (I use blaze)
I've a pagination and a update form inside 1 page. After updating a record through that form (autoform), the data list inside pagination did not updated, it just still the old one. I had to refresh the page to see the changes.

I think there's something wrong between pagination publication and updating operation.

**Comment by pipoblak** [comment]
probabbly you are using pagination and Meteor.subscribe, am i correct?

**Comment by n00bvn** [comment]
@pipoblak thanks a lot. you are right. inside controller, I do have Meteor.subcribe

**Comment by Kurounin** [comment]
@n00bvn did you manage to fix the issue? If not can you give more info, maybe a snippet of the code you're using?
