### ISSUE TITLE
Updating a record in table, doesnt update table data

### ISSUE THREAD

**Issue by amrutharamesh** [Kurounin/Pagination#63]
Hi, 

When I do an action on a row in the paginated table, which causes a change to the collection, it does not update the data in the table. I use Meteor and have the subscription as a variable outside `createContainer` and pass it down to children as props. 

```
let pagination = new Meteor.Pagination(SampleCollection, {
  name: 'list',
  perPage: 10,
  reactive: true,
  debug: true,
  sort: {}
});

export default createContainer(() => {
    return { pagination }}, Component);
```

My search, sort, and pagination work properly. But when i do an action on a row, which calls a meteor server method that updates the collection, the table doesnt have the latest data. And I have to refresh the page for it to get the latest data. What am I doing wrong?

**Comment by Kurounin** [comment]
When using it with react, I noticed that Meteor might mark the subscription as not active, depending on where the pagination instance is created and how the code is structured (see https://github.com/Kurounin/Pagination/issues/48#issuecomment-318584928 ).
Can't help you more without seeing the code.

**Comment by amrutharamesh** [comment]
Okay. I will try to structure it differently based on the react pagination example. Another question: Is there a way to check if the user is currently logged in and only then publish data ? Because when using `Meteor.publish` I could access `this.userId` and check if that value is valid. But using `publishPagination` is there a way I could specify a condition like that before publishing the data?

**Comment by amrutharamesh** [comment]
And with the respect to data not loading reactively, is there a way I can manually resubscribe ? That would help me a lot. And also I can't show you full code. So I have to figure out a way without doing that.

**Comment by Kurounin** [comment]
In regards to user specific publish, you have 2 functions available `transform_filters `and `transform_options` on server side in publishPagination. You could for example add an impossible condition when the user is not logged in:
```javascript
publishPagination(MyCollection, {
    transform_filters: function (filters, options) {
        if (!this.userId) {
                return {_id: 0};
        }

        return filters;
    },
});
```

Regarding resubscription, the pagination component automatically resubscribes anytime one of the options (filters, page, perPage, fields, sort) change. To check if that is the issue try setting a timer (or maybe https://docs.meteor.com/api/tracker.html#Tracker-afterFlush ) and change the perPage value.

**Comment by amrutharamesh** [comment]
Okay thank you.
