### ISSUE TITLE
Can't programmatically start at page one (upon route parameters refresh)

### ISSUE THREAD

**Issue by carlosalvidrez** [Kurounin/Pagination#65]
Hi, wondering if I may be doing something wrong.

I initialize the pagination on page 1, no problem... however, when the route parameter changes, which causes the collection to refresh, the refreshed route/template keeps the previous route/template page number. 

Wondering if this rings a bell, if there is any recommended turnaround, or an example about how to manipulate the page property of the pagination object... 
            Template.instance().pagination.getPage(1);  ??
            Template.instance().pagination.page = 1;   ??

Thanks!

**Comment by Kurounin** [comment]
Hi,

You can change the page by calling `Template.instance().pagination.currentPage(1)` whenever you notice a change in the url (in an _autorun_ method for example).
