### ISSUE TITLE
Server side subscription max limit

### ISSUE THREAD

**Issue by carlosalvidrez** [Kurounin/Pagination#66]
Hi, is there a way to set a limit as to the maximum number of documents the  publishPagination server-side method could ever return? 
Thanks

PS. Not sure if this should be considered an "issue", apologies if not... I just have no idea how to ask a question other than through this feature.

**Comment by Kurounin** [comment]
Hi,

You could do that in the `transform_options` method
```javascript
publishPagination(MyCollection, {
    transform_options: function (filters, options) {
        options.limit = Math.min(options.limit, 25);
        return options;
    }
});
```
But if you do this, the pagination will be wrong, since it won't know that the limit was changed server side.

**Comment by carlosalvidrez** [comment]
Understood. That worked. Many thanks!
