### ISSUE TITLE
Pagination required for multiple collections

### ISSUE THREAD

**Issue by rakesh-agrawal** [Kurounin/Pagination#71]
Hi,

We have a reports page where each record data comes from multiple collections.
Can we use this package for pagination?

We are using https://github.com/perak/meteor-joins package for joining the multiple collections in our reports page.

**Comment by Kurounin** [comment]
Hi,

To be able to use this package in conjunction with meteor-joins package, you would have to do a pagination on the main collection and in the client side, after retrieving the documents for the current page do another subscription which will retrieve the additional data needed for those documents.
