### ISSUE TITLE
Question: how to refresh the current page when reactive is false?

### ISSUE THREAD

**Issue by jvarahuayta** [Kurounin/Pagination#74]
Actually I toggle the debug property and the new records appear, but this makes logs in browser and server.

**Comment by Kurounin** [comment]
There's no officially supported method at the moment, but you can use the following to force refreshing:
`templateInstance.pagination.settings.set('resubscribe', Date.now());`

**Comment by Kurounin** [comment]
In version 1.1.0 there is a new method on client side which can be used:
```javascript
templateInstance.pagination.refresh();
```

**Comment by jvarahuayta** [comment]
Thanks!
