### ISSUE TITLE
Large datasets (500K+) creating timeouts when reactive

### ISSUE THREAD

**Issue by dariusj18** [Kurounin/Pagination#75]
It appears the library `publish-counts` creates timeouts when the observers are added to the cursor.

This seems to be a known issue with the package 

> Publish-counts is designed for counting a small number of documents around an order of 100

and also counter to the purpose of this package to be suitable for large data sets.

You may want to consider using [`publish-performant-counts`](https://atmospherejs.com/natestrauser/publish-performant-counts) or add an additional option for realtime vs interval checks and switch which package is used based on that.

**Comment by Kurounin** [comment]
Thanks for the provided solution.
I think the best solution would be to remove the current package and implement a similar solution to the one in the publish-performant-counts which would also support non-reactive publishing of counts.

**Comment by Kurounin** [comment]
Published new 1.1.0 version which implements an optimized count solution.
