### ISSUE TITLE
Question: how to keep the browser web address in sync with the page number and the page size?

### ISSUE THREAD

**Issue by carlosalvidrez** [Kurounin/Pagination#77]
Hi there!
I'd like the URL to change whenever the user changes to a certain page or changes the "per page" count, so then the URL is made restful, and can be shared. 

Hoping you have a recommendation on how to achieve that.

Thanks!

**Comment by Kurounin** [comment]
Hi,

Have a look at #34 to see how you can set the current page from the url.
Also have a look at this commit for a reactjs project https://github.com/mgscreativa/meteor-kurounin-pagination-refresh-issue/pull/2/files to see how you can set the url on a page change.
On a blaze project you could either:

- use the `autorun()` method in the `onCreated()` Template function to watch for changes to `pagination.currentPage()` and redirect to the specific url (using `window.location = ...` or `FlowRouter.go(...)` , depending on what package you might be using)
- add a handler for `onClick `event of the paginator:
```javascript
    clickEvent: function() {
        return function(e, templateInstance, clickedPage) {
            e.preventDefault();
            FlowRouter.go('/page/' + clickedPage);
        };
    }
```

**Comment by carlosalvidrez** [comment]
Understood, many thanks!
