### ISSUE TITLE
Uncaught Error: No such template: defaultBootstrapPaginator

### ISSUE THREAD

**Issue by kenshinman** [Kurounin/Pagination#8]
Hello, i got this error. when trying this package out.
`Uncaught Error: No such template: defaultBootstrapPaginator`
Any idea why this is happening or if it is a bug, is there a fix? 
Thanks

**Comment by Kurounin** [comment]
If you're using only the meteor Blaze template system, then you need to add [kurounin:pagination-blaze](https://atmospherejs.com/kurounin/pagination-blaze) package for paginator.
In case you are using React JS, you need to install either [kurounin:pagination-reactjs](https://atmospherejs.com/kurounin/pagination-reactjs) package for Meteor 1.2 or [react-bootstrap-pagination](https://www.npmjs.com/package/react-bootstrap-pagination) npm package for Meteor 1.3

**Comment by kenshinman** [comment]
Thanks a bunch

**Comment by Gibigbig** [comment]
Thanks for this. Works great.

**Comment by Kurounin** [comment]
There is a reference in the https://github.com/Kurounin/Pagination#for-blaze-template
I'll add another reference in the installation  part.
