### ISSUE TITLE
totalItems() and totalPages() always return undefined and 1

### ISSUE THREAD

**Issue by cjm27** [Kurounin/Pagination#82]
After a bit of trial and error I was able to get Pagination to work as intended perfectly, except that I cannot use `.totalPages()` or `.totalItems()` to set my data table footer correctly.

`.totalItems()` always return `undefined` and `.totalPages()` always return `1`

**Comment by Kurounin** [comment]
How are you calling `.totalItems()` ? Can you post your helper function and the template code?
