### ISSUE TITLE
How does one set a limit on the total maximum number of documents to retrieve?

### ISSUE THREAD

**Issue by carlosalvidrez** [Kurounin/Pagination#84]
For example, I want the pagination to work as usual, but to ignore all but the first 100 documents.
I hope that's clear, please let me know.
Thanks!

**Comment by Kurounin** [comment]
If you want to limit the maximum number of documents that can be retrieved at one time you can adjust the pagination option on server side: https://github.com/Kurounin/Pagination/issues/66
You could also set on server side additional filters in case you wanted to hide some specific documents.

**Comment by carlosalvidrez** [comment]
Thank you! I see I had asked this before, my apologies.
