### ISSUE TITLE
'Pagination undefined reactive subscribe' error

### ISSUE THREAD

**Issue by 95zz** [Kurounin/Pagination#86]
Pagination undefined reactive subscribe {"$text":{"$search":"document"}} {"fields":{},"sort":{"score":{"$meta":"textScore"}},"skip":0,"limit":10,"reactive":true}
meteor.js?hash=1f49b977b0beabbfeaa0ef0bdb87e0693971b18c:1048 Received error from server:  Malformed subscription

**Comment by Kurounin** [comment]
How are you using the package and on what version of meteor?
Please check [the pagination example project](https://github.com/Kurounin/PaginationExample) to ensure you're using it correctly.

**Comment by 95zz** [comment]
OK, thank you, it has been settled.
