### ISSUE TITLE
Can't get method totalItems() to work

### ISSUE THREAD

**Issue by carlosalvidrez** [Kurounin/Pagination#88]
Hi there... quick question... trying a brand new basic template... not getting the totalItems() method to work... it is returning undefined. Wondering if I missed anything in the setup.

HELPER: 
    , "totalItems": function () {
        return Template.instance().pagination.totalItems();
    }

CREATED template event snippet:
    // Pagination
    this.pagination = new Meteor.Pagination( asdf
        , {
            name: "asdf2"
            , sort: { vk:1 }
            , fields: {}
            , perPage: 12
            , page: 1
            , filters: {a:2, b:1}
            , reactive: true
            , debug: true
        }
    );

**Comment by Kurounin** [comment]
Hi,

`totalItems()` will return the number of documents only after the subscription `isReady()` and the `getPage()` was called to display the documents in the template.

**Comment by carlosalvidrez** [comment]
My mistake! Thanks... I was not using getPage on the "documents" helper.
Sorry
