### ISSUE TITLE
How to increase data per page

### ISSUE THREAD

**Issue by kenshinman** [Kurounin/Pagination#9]
How can I increase the amount of data per page?
i have tried increasing the `limit` in 
`{{> defaultBootstrapPaginator pagination=templatePagination limit=15 containerClass="text-center"}}`
but it still remains 10 (which is the default). How can i increase this to 20? Thanks

**Comment by Kurounin** [comment]
The limit parameter on the paginator modifies the maximum number of page links to display.
To modify the number of documents displayed on the page use `this.pagination.perPage(20);`
You can also pass the perPage parameter on init, like this 
 ```
   this.pagination = new Meteor.Pagination(MyCollection, {
        perPage: 20
    });
```
