### ISSUE TITLE
Multiple pagination load order

### ISSUE THREAD

**Issue by carlosalvidrez** [Kurounin/Pagination#96]
Hi! QQ. I have multiple paginations on a single page. Can I control the load order? Thing is, one of the subscriptions takes much longer than the others and it makes the others somehow wait.

Thanks

**Comment by Kurounin** [comment]
Hi,

The loading order can't be controlled, unless you do your own mechanism (using variables & autorun to trigger next subscription loading or maybe timeout for init of each subscription). Each subscription is done separately and even though it shouldn't be influenced by other subscriptions, depending on mongo indexes and performed queries it might respond slower for all subscriptions as you seem to be experiencing.
