### ISSUE TITLE
Question: are aggregate queries supported?

### ISSUE THREAD

**Issue by carlosalvidrez** [Kurounin/Pagination#97]
Wondering if I can paginate an aggregated query using this library.
Thanks!

**Comment by Kurounin** [comment]
This library doesn't support aggregated queries. It was designed to work only with filters for the find method.
The main issue with aggregation (at least at the time of writing this library) was the reactive part, as you couldn't observe changes in real time. Now there seems to be some packages that add this functionality, but I didn't try them personally so I can't say how good they work and/or if they could be integrated with pagination.

**Comment by carlosalvidrez** [comment]
Got it thanks for your prompt response, as always.
You rock!
