### ISSUE TITLE
How to catch the event when pagination is ready, AND the corresponding DOM elements finished rendering?

### ISSUE THREAD

**Issue by carlosalvidrez** [Kurounin/Pagination#98]
Hi there, just wondering if you have a method for this or a recommendation. I can catch when the page is ready with your .ready() method, beauty. Now, how can I know when the corresponding dynamic elements have been rendered? 

That way I'll know when to tigger a javascript to, for example, scroll to the newest load document.

Thanks

**Comment by Kurounin** [comment]
Hi,

Try using `Tracker.afterFlush` when `.ready()` is triggered.

**Comment by carlosalvidrez** [comment]
Will do, thanks again!
